server:
  port: 8081

spring:
  application:
    name: insurance-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/insurance_db}
    username: ${SPRING_DATASOURCE_USERNAME:insurance_user}
    password: ${SPRING_DATASOURCE_PASSWORD:insurance_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
